language: android
android:
    components:
        - build-tools-25.0.3
        - android-25
        - extra
script:
    - jdk_switcher use oraclejdk8
    - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;24.0.3"
    - cd Rxalert && ./build.sh	
