language: android
android:
    components:
        - build-tools-25.0.3
        - android-25
        - extra
script:
    - jdk_switcher use oraclejdk8
    - android update sdk --no-ui --all --filter build-tools-25.0.1,android-25,extra-android-m2repository
    - cd Rxalert && ./build.sh	
